"""Add UUID field to leads

Revision ID: 0c2aa8f5dbc8
Revises: 783581f29abb
Create Date: 2025-09-26 13:31:12.974440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c2aa8f5dbc8'
down_revision: Union[str, None] = '783581f29abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, add the column as nullable
    op.add_column('leads', sa.Column('uuid', sa.UUID(), nullable=True))

    # Generate UUIDs for existing records
    import uuid
    op.execute("UPDATE leads SET uuid = gen_random_uuid() WHERE uuid IS NULL")

    # Now make the column NOT NULL
    op.alter_column('leads', 'uuid', nullable=False)
    op.create_index(op.f('ix_leads_uuid'), 'leads', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_uuid'), table_name='leads')
    op.drop_column('leads', 'uuid')
    # ### end Alembic commands ###
