"""Add failed_emails table

Revision ID: 73d3ff3538d7
Revises: 0c2aa8f5dbc8
Create Date: 2025-09-26 14:09:37.780560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73d3ff3538d7'
down_revision: Union[str, None] = '0c2aa8f5dbc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('lead_uuid', sa.UUID(), nullable=False),
    sa.Column('lead_name', sa.String(), nullable=False),
    sa.Column('lead_email', sa.String(), nullable=False),
    sa.Column('attorney_emails', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='email_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_emails_id'), 'failed_emails', ['id'], unique=False)
    op.create_index(op.f('ix_failed_emails_lead_uuid'), 'failed_emails', ['lead_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_failed_emails_lead_uuid'), table_name='failed_emails')
    op.drop_index(op.f('ix_failed_emails_id'), table_name='failed_emails')
    op.drop_table('failed_emails')
    # ### end Alembic commands ###
