"""Initial migration

Revision ID: 783581f29abb
Revises:
Create Date: 2025-09-26 12:59:44.795703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '783581f29abb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, add the column as nullable
    op.add_column('users', sa.Column('role', sa.Enum('ATTORNEY', 'ADMIN', name='user_role'), nullable=True))

    # Update existing users to have ATTORNEY role (default)
    op.execute("UPDATE users SET role = 'ATTORNEY' WHERE role IS NULL")

    # Now make the column NOT NULL
    op.alter_column('users', 'role', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
